# Generated by Django 4.1 on 2023-07-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("Sr_No", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Item_Name",
                    models.CharField(
                        choices=[
                            ("option1", "Option 1"),
                            ("option2", "Option 2"),
                            ("option3", "Option 3"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Purchase_Quantity", models.CharField(default="", max_length=100)),
                ("Cost_Per_Item", models.CharField(default="", max_length=100)),
                ("Other_Cost", models.CharField(default="", max_length=100)),
                (
                    "Vendor_Name",
                    models.CharField(
                        choices=[
                            ("option1", "Option 1"),
                            ("option2", "Option 2"),
                            ("option3", "Option 3"),
                            ("option4", "Option 4"),
                            ("option5", "Option 5"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("Date_of_Purchase", models.DateField()),
                ("Surat_Stock", models.IntegerField()),
                ("Daman_Stock", models.IntegerField()),
                ("Ankleshvar_Stock", models.IntegerField()),
                ("Reorder_Quantity", models.CharField(max_length=100)),
            ],
        ),
    ]
