# Generated by Django 4.1 on 2023-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0003_alter_inventory_item_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Item_Name",
                    models.CharField(
                        choices=[
                            ("option1", "Option 1"),
                            ("option2", "Option 2"),
                            ("option3", "Option 3"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Item_Code", models.CharField(default="", max_length=30)),
            ],
        ),
    ]
