# Generated by Django 4.1 on 2023-08-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0004_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="id",
        ),
        migrations.AddField(
            model_name="item",
            name="Sr_No",
            field=models.IntegerField(default="0", primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="item",
            name="inventory",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="usms.inventory",
            ),
        ),
    ]
