# Generated by Django 4.1 on 2023-08-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0005_remove_item_id_item_sr_no_item_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Sr_No",
            field=models.AutoField(default="0", primary_key=True, serialize=False),
        ),
    ]
