# Generated by Django 4.1 on 2023-08-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0006_alter_item_sr_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Sr_No",
            field=models.IntegerField(default="0", primary_key=True, serialize=False),
        ),
    ]
