# Generated by Django 4.1 on 2023-08-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0007_alter_item_sr_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="Item_Name",
        ),
    ]
