# Generated by Django 4.1 on 2023-08-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0008_remove_item_item_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
