# Generated by Django 4.1 on 2023-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0010_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="Cost_Per_Item",
            field=models.IntegerField(default=""),
        ),
    ]
