# Generated by Django 4.1 on 2023-08-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usms", "0011_alter_inventory_cost_per_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="Reorder_Quantity",
            field=models.IntegerField(default=""),
        ),
    ]
